# Configuración global de imágenes
images:
  repository: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo
  # Sobrescribe el tag predeterminado que toma del appVersion del Chart
  tag: ""

# Parámetros de Seguridad y Autenticación
auth:
  adminSecretKey: "super-secret-admin-token-2026"

# Configuración de la Base de Datos PostgreSQL (Reseñas y Compras Verificadas)
database:
  enabled: true
  host: "postgres-review-db"
  port: 5432
  dbName: "reviewdb"
  username: "postgres"
  password: "postgres-secure-password-123"

# Configuración del Review Service
reviewservice:
  enabled: true
  name: reviewservice
  replicaCount: 1
  image:
    repository: "docker.io/demo/reviewservice"
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  env:
    enableAdminApi: "true"
    checkoutServiceAddr: "checkoutservice:5050"

# Cuentas de Servicio (ServiceAccounts)
serviceAccounts:
  create: true
  annotations: {}
  annotationsOnlyForCartservice: false

# Políticas de Red e Istio
networkPolicies:
  create: false

sidecars:
  create: false

authorizationPolicies:
  create: false

opentelemetryCollector:
  create: false
  name: opentelemetrycollector
  projectId: "PROJECT_ID"

googleCloudOperations:
  profiler: false
  tracing: false
  metrics: false

seccompProfile:
  enable: false
  type: RuntimeDefault

securityContext:
  enable: true

# Configuración de Microservicios Base
adService:
  create: true
  name: adservice
  resources:
    requests:
      cpu: 200m
      memory: 180Mi
    limits:
      cpu: 300m
      memory: 300Mi

cartService:
  create: true
  name: cartservice
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

checkoutService:
  create: true
  name: checkoutservice
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

currencyService:
  create: true
  name: currencyservice
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

emailService:
  create: true
  name: emailservice
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

frontend:
  create: true
  name: frontend
  externalService: true
  cymbalBranding: false
  platform: local
  singleSharedSession: false
  service:
    type: ClusterIP
    port: 80
  virtualService:
    create: false
    hosts:
    - "*"
    gateway:
      name: asm-ingressgateway
      namespace: asm-ingress
      labelKey: asm
      labelValue: ingressgateway
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  env:
    reviewServiceAddr: "reviewservice:8080"
    enableAdminPanel: "true"

loadGenerator:
  create: true
  name: loadgenerator
  checkFrontendInitContainer: true
  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

paymentService:
  create: true
  name: paymentservice
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

productCatalogService:
  create: true
  name: productcatalogservice
  extraLatency: ""
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

recommendationService:
  create: true
  name: recommendationservice
  resources:
    requests:
      cpu: 100m
      memory: 220Mi
    limits:
      cpu: 200m
      memory: 450Mi

shippingService:
  create: true
  name: shippingservice
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

cartDatabase:
  type: redis
  connectionString: "redis-cart:6379"
  inClusterRedis:
    create: true
    name: redis-cart
    publicRepository: true
  externalRedisTlsOrigination:
    enable: false
    name: exernal-redis-tls-origination
    endpointAddress: ""
    endpointPort: ""
    certificate: ""

shoppingAssistantService:
  create: false
  name: shoppingassistantservice