apiVersion: v1
kind: Secret
metadata:
  name: reviewservice-secrets
  labels:
    {{- include "onlineboutique.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_SECRET_KEY: {{ .Values.auth.adminSecretKey | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}