apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviewservice
  template:
    metadata:
      labels:
        app: reviewservice
    spec:
      containers:
      - name: server
        image: 414931564967.dkr.ecr.us-east-1.amazonaws.com/online-boutique/reviewservice:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: reviewservice
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: reviewservice
